name: Read secret
on: push
jobs:
  read-secret-job:
    runs-on: ubuntu-latest
    env:
      MY_ENV_VAR: "dit is een environment variable"
    steps:
      - name: print the secret
        run: echo "my is secret is ${{ secrets.MY_SECRET }}"
      - name: print environment variable
        run: echo "env var is $MY_ENV_VAR"
